#checkov:skip=CKV_DOCKER_2: it's a lambda function image, doesn't need healthcheck
#checkov:skip=CKV_DOCKER_3: it's a lambda function image, we would not be able add an user
FROM amazon/aws-lambda-python:3.9

LABEL maintainer="Denys Gonzaga"
RUN yum update -y && \
    yum install -y python3 python3-dev python3-pip gcc && \
    rm -Rf /var/cache/yum

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY main.py ./
CMD ["main.handler"]